name: Code Check

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.4"
      - name: pub get
        run: make install
      - name: test
        run: make testing
